# Language configurations
LANGUAGES = {
    "zh": {
        "page_title": "图片查看器",
        "sidebar_title": "🖼️ 图片查看器",
        "input_mode_label": "输入模式",
        "input_mode_json": "JSON 配置文件",
        "input_mode_folders": "文件夹列表",
        "upload_label": "上传 JSON 配置文件",
        "upload_help": "上传包含图片路径和方法信息的 JSON 文件",
        "folder_list_label": "输入文件夹路径（每行一个）",
        "folder_list_help": "每个文件夹代表一个方法，文件夹名即为方法名",
        "folder_list_placeholder": "例如：\n./images/method_A\n./images/method_B\n./images/method_C",
        "no_file_msg": "👈 请在左侧上传 JSON 配置文件开始使用",
        "no_folder_msg": "👈 请在左侧输入文件夹路径开始使用",
        "json_example_title": "📄 查看 JSON 格式示例",
        "folder_example_title": "📁 查看文件夹列表示例",
        "loading_summary_title": "📊 加载摘要",
        "num_methods_label": "方法数量",
        "num_samples_label": "样本数量",
        "num_missing_label": "缺失图片",
        "image_missing_placeholder": "图片缺失",
        "error_no_folders": "请至少输入一个文件夹路径",
        "error_folder_not_exist": "文件夹不存在",
        "error_no_images_in_folder": "在文件夹中未找到图片文件",
        "sample_selection": "📂 样本选择",
        "num_rows_label": "显示行数",
        "num_rows_help": "选择同时显示多少行样本",
        "starting_sample": "起始样本",
        "prev_button": "上一个",
        "next_button": "下一个",
        "current_label": "📍 当前",
        "range_label": "📍 显示范围",
        "close_view": "🔍 Close View",
        "enable": "启用",
        "close_view_help": "启用裁剪功能以查看所有方法的详细区域",
        "show_edit_button": "显示Edit按钮",
        "show_edit_help": "控制是否显示编辑裁剪按钮",
        "clear_all_crops": "Clear All Crops",
        "display_options": "🎨 显示选项",
        "show_sample_name": "显示样本标题 (Sample Name)",
        "show_method_name": "显示方法名称 (Method Name)",
        "show_text": "显示样本文本 (Text)",
        "show_descriptions": "显示方法说明 (Descriptions)",
        "reference": "Reference",
        "method_display": "🎯 方法显示",
        "select_methods": "选择要显示的方法",
        "instructions": "📖 使用说明",
        "edit_crop": "✏️ Edit",
        "delete_crop": "🗑️ Delete",
        "add_crop": "➕ Add Crop",
        "max_crops_msg": "最多支持 {n} 个Close Views",
        "method_desc_title": "方法说明",
        "aspect_ratio_warning": "⚠️ 宽高比警告 - 点击查看详情",
        "aspect_ratio_msg": "检测到部分图片宽高比存在差异：",
        "select_reference_image": "选择参考图片：",
        "error_no_images": "未找到有效的图片",
        "draw_crop_hint": "👆 在上方图片上绘制矩形以选择裁剪区域",
        "reference_image": "参考图片",
        "close_view_preview": "Close View 预览",
        "draw_crop_to_preview": "在左侧绘制裁剪框以查看预览",
        "crop_size_label": "裁剪尺寸",
        "valid_methods_count": "可用参考图片: {n}/{total}",
        "no_valid_reference": "没有可用的参考图片",
        "text_size_label": "Prompt文本大小",
        "text_size_help": "调整样本文本显示大小（10-24px）",
        "method_text_size_label": "方法文本大小",
        "method_text_size_help": "调整方法名称和说明显示大小（10-24px）",
        "preserve_aspect_ratio": "保持原始比例",
        "preserve_aspect_ratio_help": "不裁剪为正方形，完整显示图片",
        "save_pdf_tooltip": "保存当前页面为PDF",
        "save_pdf_disabled_tooltip": "请先完成裁剪编辑",
        "save_pdf_generating": "正在生成PDF...",
        "save_pdf_filename": "图片查看器导出",
        "use_mask": "使用 Mask",
        "use_mask_help": "对图片应用 mask 效果：mask > 0 的区域正常显示，其余区域变暗",
        "darken_factor_label": "变暗系数",
        "darken_factor_help": "mask = 0 区域变暗的系数",
    },
    "en": {
        "page_title": "ImageViewer",
        "sidebar_title": "🖼️ ImageViewer",
        "input_mode_label": "Input Mode",
        "input_mode_json": "JSON Configuration",
        "input_mode_folders": "Folder List",
        "upload_label": "Upload JSON Configuration",
        "upload_help": "Upload a JSON file containing image paths and method information",
        "folder_list_label": "Enter folder paths (one per line)",
        "folder_list_help": "Each folder represents a method, folder name is the method name",
        "folder_list_placeholder": "Example:\n./images/method_A\n./images/method_B\n./images/method_C",
        "no_file_msg": "👈 Please upload a JSON configuration file in the sidebar",
        "no_folder_msg": "👈 Please enter folder paths in the sidebar",
        "json_example_title": "📄 View JSON Format Example",
        "folder_example_title": "📁 View Folder List Example",
        "loading_summary_title": "📊 Loading Summary",
        "num_methods_label": "Number of Methods",
        "num_samples_label": "Number of Samples",
        "num_missing_label": "Missing Images",
        "image_missing_placeholder": "Image Missing",
        "error_no_folders": "Please enter at least one folder path",
        "error_folder_not_exist": "Folder does not exist",
        "error_no_images_in_folder": "No image files found in folder",
        "sample_selection": "📂 Sample Selection",
        "num_rows_label": "Number of Rows",
        "num_rows_help": "Select how many rows of samples to display simultaneously",
        "starting_sample": "Starting Sample",
        "prev_button": "Previous",
        "next_button": "Next",
        "current_label": "📍 Current",
        "range_label": "📍 Range",
        "close_view": "🔍 Close View",
        "enable": "Enable",
        "close_view_help": "Enable cropping feature to view detailed regions across all methods",
        "show_edit_button": "Show Edit Button",
        "show_edit_help": "Control whether to show edit crop buttons",
        "clear_all_crops": "Clear All Crops",
        "display_options": "🎨 Display Options",
        "show_sample_name": "Show Sample Name",
        "show_method_name": "Show Method Name",
        "show_text": "Show Sample Text",
        "show_descriptions": "Show Method Descriptions",
        "reference": "Reference",
        "method_display": "🎯 Method Display",
        "select_methods": "Select methods to display",
        "instructions": "📖 Instructions",
        "edit_crop": "✏️ Edit",
        "delete_crop": "🗑️ Delete",
        "add_crop": "➕ Add Crop",
        "max_crops_msg": "Maximum {n} Close Views supported",
        "method_desc_title": "Method Descriptions",
        "aspect_ratio_warning": "⚠️ Aspect Ratio Warning - Click for details",
        "aspect_ratio_msg": "Detected aspect ratio differences in some images:",
        "select_reference_image": "Select reference image:",
        "error_no_images": "No valid images found",
        "draw_crop_hint": "👆 Draw a rectangle on the image above to select the crop area",
        "reference_image": "Reference Image",
        "close_view_preview": "Close View Preview",
        "draw_crop_to_preview": "Draw a crop box on the left to see preview",
        "crop_size_label": "Crop size",
        "valid_methods_count": "Available images: {n}/{total}",
        "no_valid_reference": "No valid reference images available",
        "text_size_label": "Prompt Text Size",
        "text_size_help": "Adjust sample text display size (10-24px)",
        "method_text_size_label": "Method Text Size",
        "method_text_size_help": "Adjust method name and description display size (10-24px)",
        "preserve_aspect_ratio": "Preserve aspect ratio",
        "preserve_aspect_ratio_help": "Display full image without cropping to square",
        "save_pdf_tooltip": "Save current page as PDF",
        "save_pdf_disabled_tooltip": "Please finish crop editing first",
        "save_pdf_generating": "Generating PDF...",
        "save_pdf_filename": "image_viewer_export",
        "use_mask": "Use Mask",
        "use_mask_help": "Apply mask effect: show mask > 0 areas normally, darken others",
        "darken_factor_label": "Darken Factor",
        "darken_factor_help": "Darken factor for mask = 0 regions",
    },
}
